replicaCount: 2

image:
  repository: tyaminilya/muffin-currency
  tag: "2.0.0"
  pullPolicy: Always

service:
  type: ClusterIP
  port: 8080
  targetPort: 8080

containerPort: 8080

probes:
  liveness:
    path: /rate?from=PLAIN&to=CHOKOLATE
    initialDelaySeconds: 10
    periodSeconds: 10
  readiness:
    path: /rate?from=PLAIN&to=CHOKOLATE
    initialDelaySeconds: 10
    periodSeconds: 5

autoscaling:
  enabled: false

ingress:
  enabled: false
  className: nginx
  annotations: {}
  hosts:
    - host: "muffin-currency.com"
      paths:
        - path: /
          pathType: Prefix
  tls: []

serviceAccount:
  create: true
  name: muffin-wallet

env:
  - name: OTEL_EXPORTER_OTLP_ENDPOINT
    value: opentelemetry-collector.wallet-monitoring.svc.cluster.local:4317