replicaCount: 1

image:
  repository: tyaminilya/muffin-wallet
  tag: "2.0.1"
  pullPolicy: Always

service:
  type: ClusterIP
  port: 8081
  targetPort: 8081

containerPort: 8081

probes:
  liveness:
    path: /actuator/health/liveness
    initialDelaySeconds: 10
    periodSeconds: 10
  readiness:
    path: /actuator/health/readiness
    initialDelaySeconds: 10
    periodSeconds: 5

autoscaling:
  enabled: false

ingress:
  enabled: false
  className: nginx
  annotations: {}
  hosts:
    - host: "muffin-wallet.com"
      paths:
        - path: /
          pathType: Prefix
  tls: []

env:
  - name: SPRING_DATASOURCE_URL
    value: "jdbc:postgresql://host.minikube.internal:5432/postgres"
  - name: SPRING_DATASOURCE_USERNAME
    value: "postgres"
  - name: SPRING_DATASOURCE_PASSWORD
    value: "postgres"
  - name: SERVER_PORT
    value: "8081"
  - name: SPRING_PROFILES_ACTIVE
    value: "default"
  - name: SPRING_MAIN_LOGGING_LEVEL
    value: "DEBUG"
  - name: SPRING_BOOT_LOGGING_DEBUG
    value: "true"
  - name: CURRENCY_SERVICE_URL
    value: "http://muffin-currency:8080/rate"
  - name: MANAGEMENT_ENDPOINTS_WEB_EXPOSURE_INCLUDE
    value: "health,info,prometheus,metrics"
  - name: MANAGEMENT_METRICS_EXPORT_PROMETHEUS_ENABLED
    value: "true"
  - name: MANAGEMENT_METRICS_DISTRIBUTION_PERCENTILES-HISTOGRAM_HTTP_SERVER_REQUESTS
    value: "true"
  - name: MANAGEMENT_METRICS_DISTRIBUTION_SLA_HTTP_SERVER_REQUESTS
    value: "100ms,200ms,500ms,1s,2s"
  - name: MANAGEMENT_METRICS_TAGS_APPLICATION
    value: "muffin-wallet"
  - name: MANAGEMENT_ZIPKIN_TRACING_CONNECT_TIMEOUT
    value: 5s
  - name: MANAGEMENT_ZIPKIN_TRACING_READ_TIMEOUT
    value: 5s
  - name: MANAGEMENT_ZIPKIN_TRACING_MESSAGE_TIMEOUT
    value: 5s
  - name: MANAGEMENT_TRACING_PROPAGATION_TYPE
    value: B3
  - name: OTEL_INSTRUMENTATION_MICROMETER_ENABLED
    value: "true"
  - name: OTEL_EXPORTER_OTLP_ENDPOINT
    value: "http://opentelemetry-collector.wallet-monitoring.svc.cluster.local:4318"
  - name: OTEL_RESOURCE_ATTRIBUTES
    value: "service.name=muffin-wallet"
  - name: JAVA_TOOL_OPTIONS
    value: "-javaagent:/otel-javaagent/opentelemetry-javaagent.jar"

podAnnotations:
  prometheus.io/scrape: "true"
  prometheus.io/path: "/actuator/prometheus"
  prometheus.io/port: "8081"