image:
  repository: otel/opentelemetry-collector-contrib
  tag: 0.98.0

mode: deployment

service:
  type: ClusterIP

config:
  receivers:
    otlp:
      protocols:
        grpc:
          endpoint: "0.0.0.0:4317"
        http:
          endpoint: "0.0.0.0:4318"
    jaeger:
      protocols:
        grpc:
          endpoint: "0.0.0.0:14250"
        thrift_compact:
          endpoint: "0.0.0.0:6831"
        thrift_http:
          endpoint: "0.0.0.0:14268"
    prometheus:
      config:
        scrape_configs:
          - job_name: opentelemetry-collector
            scrape_interval: 10s
            static_configs:
              - targets:
                  - "0.0.0.0:8888"
          - job_name: "muffin-wallet"
            scrape_interval: 3s
            metrics_path: /actuator/prometheus
            static_configs:
              - targets: [ "muffin-wallet.default.svc.cluster.local:8081" ]


  processors:
    batch: { }
    memory_limiter:
      check_interval: 5s
      limit_percentage: 80
      spike_limit_percentage: 25

  exporters:
    zipkin:
      endpoint: "http://zipkin.wallet-monitoring.svc.cluster.local:9411/api/v2/spans"
    # https://grafana.com/docs/loki/latest/send-data/otel/
    otlphttp:
      endpoint: "http://loki.wallet-monitoring.svc.cluster.local:3100/otlp"
    debug: { }
    prometheus:
      endpoint: "0.0.0.0:8890"

  extensions:
    health_check: { }

  service:
    extensions:
      - health_check

    pipelines:
      logs:
        receivers: [otlp]
        processors: [memory_limiter, batch]
        exporters: [otlphttp, debug]

      metrics:
        receivers: [otlp, prometheus]
        processors: [memory_limiter, batch]
        exporters: [prometheus, debug]

      traces:
        receivers: [otlp, jaeger]
        processors: [memory_limiter, batch]
        exporters: [zipkin, debug]

    telemetry:
      metrics:
        address: "0.0.0.0:8889"